  language: node_js
  node_js: 5
  install:
    - npm install
    - npm install -g codecov
  env:
    global:
      - CODECOV_TOKEN: 081f6598-3a16-4eb6-a14c-3ede7a302a78
  script:
    - istanbul cover ./node_modules/mocha/bin/_mocha
    - codecov

